### PR TITLE
Enable cross-cluster monitor cluster setting

### PR DESCRIPTION
**Pull request by goyamegh**
*Issue #, if available:*

*Description of changes:*
Enable cross-cluster monitor cluster setting

*CheckList:*
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/alerting/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by AWSHurneyt — APPROVED** [review]

**Comment by AWSHurneyt** [comment]
Approving assuming CI passes.

**Comment by AWSHurneyt** [comment]
Backporting back to v2.14 as the feature received GA launch approval after 2.13 open source release.

**Comment by AWSHurneyt** [comment]
The failing test is `org.opensearch.alerting.transport.GetRemoteIndexesActionIT > test with remote monitoring disabled`.
https://github.com/opensearch-project/alerting/actions/runs/9999216318/job/27639794066?pr=1612#step:5:334

That test suite has a helper function which should be toggling the feature on/off; but it looks like it's failing to disable to feature before the start of that test. Troubleshooting that test.

**Comment by AWSHurneyt** [comment]
> The failing test is `org.opensearch.alerting.transport.GetRemoteIndexesActionIT > test with remote monitoring disabled`. https://github.com/opensearch-project/alerting/actions/runs/9999216318/job/27639794066?pr=1612#step:5:334
> 
> That test suite has a helper function which should be toggling the feature on/off; but it looks like it's failing to disable to feature before the start of that test. Troubleshooting that test.

Fixed in commit https://github.com/opensearch-project/alerting/pull/1612/commits/478eb4680dfe842f113e91e9c5844d0fbeb9fa0d

**Review by AWSHurneyt — APPROVED** [review]

**Review by jowg-amazon — APPROVED** [review]

**Pull request merged**
