### PR TITLE
support query deletion from custom query index on delete monitor

### PR DESCRIPTION
**Pull request by eirsep**
Signed-off-by: Surya Sashank Nistala <snistala@amazon.com>

*Issue #, if available:*
#581

### CODE REVIEW

**Comment by sbcd90** [comment]
@eirsep @getsaurabh02 one issue with the `alerting delete` api is it is asynchronous. when it returns, it doesnt guarantee that data & index is cleaned up or not.
do we want to fix it as part of this pr otherwise `security-analytics` may not be able to delete the `rule index`?

**Comment by eirsep** [comment]
> @eirsep @getsaurabh02 one issue with the `alerting delete` api is it is asynchronous. when it returns, it doesnt guarantee that data & index is cleaned up or not. do we want to fix it as part of this pr otherwise `security-analytics` may not be able to delete the `rule index`?

We should not do asynchronous deletes IMO. We can leave around a lot of dangling resources if we don't do synchronous chaining.

**Comment by getsaurabh02** [comment]
Lets open an issue to discuss the delete behavior for Alerting monitors and reason why was it made async in the first place. Can be out of the scope for this PR

**Review by getsaurabh02 — APPROVED** [review]

**Review by sbcd90 — APPROVED** [review]

**Comment by eirsep** [comment]
https://github.com/opensearch-project/alerting/issues/586

**Pull request merged**
