### PR TITLE
Incremented version to 2.1.1.

### PR DESCRIPTION
**Pull request by gaiksaya**
Coming from https://github.com/opensearch-project/opensearch-build/issues/1818 post release activities.

### CODE REVIEW

**Comment by AWSHurneyt** [comment]
Alerting depends on Notificaitons, so this PR will need to be resolved and merged before this one.
https://github.com/opensearch-project/notifications/pull/478

**Comment by gaiksaya** [comment]
@AWSHurney the above PR is merged. So you need to snapshot for this to pass?
If yes we might need to add notifications to 2.1.1 manifest.
Lmk
Thanks!

**Comment by AWSHurneyt** [comment]
> @AWSHurney the above PR is merged. So you need to snapshot for this to pass? If yes we might need to add notifications to 2.1.1 manifest. Lmk Thanks!

@gaiksaya yes, we'll need a snapshot for the build and tests to execute.

**Comment by gaiksaya** [comment]
Created a PR https://github.com/opensearch-project/opensearch-build/pull/2449 to add notifications

**Comment by gaiksaya** [comment]
Closing this as 2.2.0 is released and this version will not be out now.
Thanks!

**Pull request closed without merging**
