### PR TITLE
Update alerting with qualifier support in releases

### PR DESCRIPTION
**Pull request by peterzhuamazon**
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>

*Issue #, if available:*
#348

*Description of changes:*
Update alerting with qualifier support in releases

*CheckList:*
[x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/alerting/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
@lezzago seems like your test is failing I am not sure if it is compatible with 2.0.0-alpha1 as of yet. Can you guys take a look on this?

Thanks.

**Review by lezzago — APPROVED** [review]

**Comment by lezzago** [comment]
> 

We will submit a new pr later to fix those test issues since there are more 2.0 breaking changes

**Comment by qreshi** [comment]
This doesn't just look like test failures, it's failing to build with OpenSearch 2.0.0-alpha1. We should make the appropriate changes in this PR to fix compile issues, etc.

@peterzhuamazon If you'd like to avoid that, you can just make the build qualifier changes here but keep using `2.0.0` for OpenSearch instead of `2.0.0-alpha1`. Then I can look into the errors of bumping to alpha1. I want to avoid breaking main.

**Comment by peterzhuamazon** [comment]
After talking to alerting team I will keep 2.0.0-SNAPSHOT for the time being to merge this PR.

They will fix the compiling issues on alpha1 and add back.

Thanks.

**Review by qreshi — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
Merge this as the security plugin is not available yet, so security checks expected to fail here.

**Pull request merged**
