### PR TITLE
Staging for version increment automation

### PR DESCRIPTION
**Pull request by prudhvigodithi**
Signed-off-by: pgodithi <pgodithi@amazon.com>

*Issue #, if available:*
Part of: https://github.com/opensearch-project/opensearch-build/issues/1375
From solution: https://github.com/opensearch-project/opensearch-build/issues/1375#issuecomment-1159476686
Related issue: https://github.com/opensearch-project/alerting/issues/482

*Description of changes:*
This is the staging PR for to execute workflows that auto raise the version increment PR's
Example: https://github.com/prudhvigodithi/alerting/pull/1

*CheckList:*
[ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/alerting/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by prudhvigodithi** [comment]
Referred old version increment PR's
https://github.com/opensearch-project/alerting/pull/488
https://github.com/opensearch-project/alerting/pull/465

**Comment by prudhvigodithi** [comment]
Renaming to task updateVersion following https://github.com/opensearch-project/opensearch-plugin-template-java/pull/32.

**Comment by prudhvigodithi** [comment]
Hey @lezzago @praveensameneni can you please take a look.
Thank you

**Comment by bbarani** [comment]
@lezzago @praveensameneni can you please review this PR soon?

**Review by lezzago — APPROVED** [review]

**Review by AWSHurneyt — APPROVED** [review]

**Comment by prudhvigodithi** [comment]
Hey @lezzago can you please take care of all the backport PR's? ;)

**Pull request merged**
